services:
  spelunker:
    extends:
      file: docker-compose.yml
      service: spelunker
    image: spelunker:${RELEASE_TAG:-latest}
    ports:
      - 8888:80
    restart: unless-stopped
    env_file:
      - ./.env
    labels:
      - traefik.enable=false

  elasticsearch:
    extends:
      file: docker-compose.yml
      service: elasticsearch
    ports:
      - 9200:9200

  kibana:
    image: docker.elastic.co/kibana/kibana:${ELASTICSEARCH_TAG:-latest}
    depends_on:
      - elasticsearch
    networks:
      - woeplanet-backend
    expose:
      - 5601
    ports:
      - 5601:5601
    restart: unless-stopped
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200

networks:
  woeplanet-backend:
    external: true
